### ISSUE TITLE
Compilation errors on mac

### ISSUE THREAD

**Issue by eitanp461** [kperwel/images-manager#1]
I had to rename a few files due to case sensitivity issues.

I got this error - 

```
Failed to compile.

./src/components/index.ts
Cannot find file: 'Tile.tsx' does not match the corresponding name on disk: './src/components/tile.tsx'.

```

These are the files that I had to rename - `Grid.tsx`, `Image.tsx`, `Tile.tsx`

**Comment by kperwel** [comment]
Thanks. I've pushed fix directly to the master branch.
`git mv --force filename Filename` did the job.

https://coderwall.com/p/mgi8ja/case-sensitive-git-in-mac-os-x-like-a-pro
